const showChamp = document.getElementById('champPickElement');
const typeOfChamp = document.getElementById('underlined');

const champs = [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "Aurelion Sol",
    "Azir",
    "Bard",
    "Bel'Veth",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Cho'Gath",
    "Corki",
    "Darius",
    "Diana",
    "Dr.Mundo",
    "Draven",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "Jarvan IV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kai'Sa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Kha'Zix",
    "Kindred",
    "Kled",
    "K'Sante",
    "Kog'Maw",
    "LeBlanc",
    "Lee Sin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Master Yi",
    "Milio",
    "Miss Fortune",
    "Mordekaiser",
    "Morgana",
    "Naafiri",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu & Willump",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "Rek'Sai",
    "Rell",
    "Renata Glasc",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "Tahm Kench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "Twisted Fate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Vel'Koz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Wukong",
    "Xayah",
    "Xerath",
    "Xin Zhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra"
];

const adcChamps = [
    "Aphelios",
    "Ashe",
    "Caitlyn",
    "Draven",
    "Ezreal",
    "Graves",
    "Jhin",
    "Jinx",
    "Kai'Sa",
    "Kalista",
    "Karthus",
    "Kog'Maw",
    "Lucian",
    "Miss Fortune",
    "Nilah",
    "Samira",
    "Seraphine"
    "Sivir",
    "Tristana",
    "Twitch",
    "Varus",
    "Vayne",
    "Xayah"
    "Zeri",
    "Ziggs"
];

const supportChamps = [
    "Alistar",
    "Amumu",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Galio",
    "Heimerdinger",
    "Janna",
    "Karma",
    "Leona",
    "Lulu",
    "Lux",
    "Maokai",
    "Milio",
    "Morgana",
    "Nami",
    "Nautilus",
    "Neeko",
    "Pantheon",
    "Pyke",
    "Rakan",
    "Rell"
    "Renata Gasc",
    "Senna",
    "Seraphine",
    "Shaco",
    "Sona",
    "Soraka",
    "Swain",
    "Tahm Kench",
    "Taric",
    "Thresh",
    "Vel'Koz",
    "Xerath",
    "Yuumi",
    "Zilean",
    "Zyra"
];

const midChamps = [
    "Ahri",
    "Akali",
    "Akshan",
    "Anivia",
    "Annie",
    "Aurelion Sol",
    "Azir",
    "Cassiopeia",
    "Cho'Gath",
    "Corki",
    "Diana",
    "Ekko",
    "Fizz",
    "Galio",
    "Irelia",
    "Jayce",
    "Kassadin",
    "Katarina",
    "LeBlanc",
    "Lissandra",
    "Lux",
    "Malzahar",
    "Naafiri",
    "Neeko",
    "Orianna",
    "Pantheon",
    "Qiyana",
    "Ryze",
    "Swain",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Talon",
    "Tristana",
    "Twisted Fate",
    "Veigar",
    "Vel'Koz",
    "Vex",
    "Viktor",
    "Vladimir",
    "Xerath",
    "Yasuo",
    "Yone"
    "Zed",
    "Ziggs",
    "Zoe"
];

const jungleChamps = [
    "Amumu",
    "Bel'Veth",
    "Diana",
    "Ekko",
    "Elise",
    "Evelynn",
    "Fiddlesticks",
    "Gragas",
    "Graves",
    "Hecarim",
    "Ivern",
    "Jarvan IV",
    "Karthus",
    "Kayn",
    "Kha'Zix",
    "Kindred",
    "Lee Sin",
    "Lillia",
    "Maokai",
    "Master Yi",
    "Naafiri",
    "Nidalee",
    "Nocturne",
    "Nunu",
    "Poppy",
    "Rammus",
    "Rek'Sai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Sylas",
    "Taliyah",
    "Talon",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "Wukong",
    "Xin Zhao",
    "Zac",
];

const topChamps = [
    "Aatrox",
    "Akali",
    "Akshan",
    "Camille",
    "Cho'Gath",
    "Darius",
    "Dr.Mundo",
    "Fiora",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gwen",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Jax",
    "Jayce",
    "K'Sante",
    "Kayle",
    "Kennen",
    "Kled",
    "Malphite",
    "Mordekaiser",
    "Naafiri",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Quinn",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Sett",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Tahm Kench",
    "Teemo",
    "Trundle",
    "Tryndamere",
    "Urgot",
    "Volibear",
    "Warwick",
    "Wukong",
    "Yone",
    "Yorick",
];

function randomChampion(){
    // generating random number for all of the League champions
    const randomPickGeneral = Math.floor(Math.random() * champs.length);
    // generating random number for ADC champions.
    const randomPickADC = Math.floor(Math.random() * adcChamps.length);
    // generating random number for Support champions.
    const randomPickSupport = Math.floor(Math.random() * supportChamps.length);
    // generating random number for Mid champions.
    const randomPickMid = Math.floor(Math.random() * midChamps.length);
    // generating random number for Jungle champions.
    const randomPickJungle = Math.floor(Math.random() * jungleChamps.length);
    // generating random number for Top champions.
    const randomPickTop = Math.floor(Math.random() * topChamps.length);

    // testing the if selected in javascript
    if(document.getElementById('championRole').value == "adc") {
        typeOfChamp.innerText = "Your ADC Champ:"
        showChamp.innerText = adcChamps[randomPickADC];
    }
    if(document.getElementById('championRole').value == "general") {
        typeOfChamp.innerText = "Your Random Champ:"
        showChamp.innerText = champs[randomPickGeneral];
    }
    if(document.getElementById('championRole').value == "support") {
        typeOfChamp.innerText = "Your Support Champ:"
        showChamp.innerText = supportChamps[randomPickSupport];
    }
    if(document.getElementById('championRole').value == "mid") {
        typeOfChamp.innerText = "Your Mid Champ:"
        showChamp.innerText = midChamps[randomPickMid];
    }
    if(document.getElementById('championRole').value == "jungle") {
        typeOfChamp.innerText = "Your Jungle Champ:"
        showChamp.innerText = jungleChamps[randomPickJungle];
    }
    if(document.getElementById('championRole').value == "top") {
        typeOfChamp.innerText = "Your Top Champ:"
        showChamp.innerText = topChamps[randomPickTop];
    }

}